export const newTheme = {
  colors: {
    bg: '#0C0D10',
    bg2: '#13151A',
    bg3: '#1A1D25',
    bg4: '#21252F',
    amber: '#F5A623',
    amber2: '#FFCA6B',
    amberGlow: 'rgba(245,166,35,0.18)',
    green: '#34D399',
    greenGlow: 'rgba(52,211,153,0.15)',
    red: '#F87171',
    blue: '#60A5FA',
    blueGlow: 'rgba(96,165,250,0.12)',
    purple: '#A78BFA',
    text: '#F0F2F7',
    text2: '#8B91A6',
    text3: '#525869',
    border: 'rgba(255,255,255,0.06)',
    white: '#FFFFFF',
    black: '#000000',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 14,
    xl: 18,
    xxl: 24,
    round: 9999,
  },
  fontSize: {
    xs: 10,
    sm: 11,
    md: 12,
    base: 13,
    lg: 14,
    xl: 16,
    xxl: 18,
    xxxl: 20,
    huge: 26,
    massive: 30,
  },
  fontWeight: {
    normal: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};

export const commonStyles = {
  card: {
    backgroundColor: newTheme.colors.bg2,
    borderWidth: 1,
    borderColor: newTheme.colors.border,
    borderRadius: newTheme.borderRadius.xl,
    overflow: 'hidden',
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: newTheme.borderRadius.round,
    gap: 5,
  },
  pillGreen: {
    backgroundColor: newTheme.colors.greenGlow,
  },
  pillAmber: {
    backgroundColor: newTheme.colors.amberGlow,
  },
  pillRed: {
    backgroundColor: 'rgba(248,113,113,0.12)',
  },
  pillBlue: {
    backgroundColor: 'rgba(96,165,250,0.12)',
  },
  pillText: {
    fontSize: newTheme.fontSize.sm,
    fontWeight: newTheme.fontWeight.semibold,
  },
  h1: {
    fontSize: newTheme.fontSize.huge,
    fontWeight: newTheme.fontWeight.bold,
    color: newTheme.colors.text,
    letterSpacing: -0.5,
  },
  h2: {
    fontSize: newTheme.fontSize.xxxl,
    fontWeight: newTheme.fontWeight.semibold,
    color: newTheme.colors.text,
    letterSpacing: -0.3,
  },
  body: {
    fontSize: newTheme.fontSize.lg,
    fontWeight: newTheme.fontWeight.normal,
    color: newTheme.colors.text2,
    lineHeight: 21,
  },
  small: {
    fontSize: newTheme.fontSize.md,
    color: newTheme.colors.text3,
  },
  label: {
    fontSize: newTheme.fontSize.sm,
    fontWeight: newTheme.fontWeight.semibold,
    color: newTheme.colors.text3,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
};
